### ISSUE TITLE
Incorrect implementation of flow_st()

### ISSUE THREAD

**Issue by anianruoss** [rakutentech/stAdv#1]
In my opinion, lines 114 - 117 in layers.py should be:

```python
wa = (1. - (sampling_grid_x - x0)) * (1. - (sampling_grid_y - y0))
wb = (1. - (sampling_grid_x - x0)) * (1. - (y1 - sampling_grid_y))
wc = (1. - (x1 - sampling_grid_x)) * (1. - (sampling_grid_y - y0))
wd = (1. - (x1 - sampling_grid_x)) * (1. - (y1 - sampling_grid_y))
```
instead of:
```python
wa = (x1 - sampling_grid_x) * (y1 - sampling_grid_y)
wb = (x1 - sampling_grid_x) * (sampling_grid_y - y0)
wc = (sampling_grid_x - x0) * (y1 - sampling_grid_y)
wd = (sampling_grid_x - x0) * (sampling_grid_y - y0)
```
according to eq. (1) in Xiao et al.

Am I missing something?

**Comment by berangerd** [comment]
``x1`` and ``y1`` are defined as follows in ``layers.py``:
```python
x1 = x0 + 1
y1 = y0 + 1
```
so these two definitions of the wa, wb, wc, wd are equivalent.

The implementation of the bilinear interpolation has been tested against the one from scikit-image (up to boundary effects) in https://github.com/rakutentech/stAdv/blob/master/tests/test_layers.py#L144

**Comment by anianruoss** [comment]
Yes, of course. Thank you!
