### ISSUE TITLE
Incorrect implementation of adv_loss()

### ISSUE THREAD

**Issue by anianruoss** [rakutentech/stAdv#2]
In my opinion, line 115 in losses.py should be:
```python
return tf.maximum(L_adv_1 - L_adv_2, kappa, name='L_adv')
```
instead of:
```python
return tf.maximum(L_adv_1 - L_adv_2, - kappa, name='L_adv')
```
according to eq. (3) in Xiao et al.

Am I missing something?

**Comment by berangerd** [comment]
That's a difference in notation between Eq. (3) of Xiao et al. and Carlini & Wagner (see bottom of p. 9 in https://arxiv.org/pdf/1608.04644.pdf). Xiao et al. assume a negative kappa (well in practice they only consider kappa = 0) while Carlini & Wagner assume a positive one. As the documentation of the function ``adv_loss`` primarily refers to the Carlini & Wagner paper I think it is sufficiently clear.

**Comment by anianruoss** [comment]
Thank you for clarifying!
