### ISSUE TITLE
Test the demo in batch

### ISSUE THREAD

**Issue by RoyalVane** [rakutentech/stAdv#7]
Hi Berangerd, 
Can this demo be tested in batches? :)

**Comment by berangerd** [comment]
Yes, and that's quite straightforward. You do not need to change anything to the graph, just adapt the shape of your input images / labels / targets / flows arrays. Let me know if it doesn't work.

**Comment by RoyalVane** [comment]
I test it and find it works well on batches! Thank you for your reply! : )

**Comment by berangerd** [comment]
Good to know!

**Comment by praveern** [comment]
Hello Berangerd, can I ask about how to switch tensorflow session.run( ) commands to make it work for batch demo? Forgive me for the stupid question, I'm a beginner in TensorFlow, and I was getting confused.
 
Hello RoyalVane, may I please ask where did you make changes when it came to the session.run( ) section? I selected 5 random images and their corresponding labels from the test_data. I also generated random targets for each image.
