### ISSUE TITLE
How to change the dimension while generating the flows?

### ISSUE THREAD

**Issue by praveern** [rakutentech/stAdv#9]
What are the suitable values for the flows variable? We were trying to change the dimension parameter from 2 to 1. However this seems incorrect.

Please help, thanks!

**Comment by berangerd** [comment]
It can be found in the [doc](https://stadv.readthedocs.io/en/latest/stadv.html):
> flows (tf.Tensor) – flows of shape (B, 2, H, W), where the second dimension indicates the dimension on which the pixel shift is applied

where B is the batch size, and H and W is the height and width of the input images.

**Comment by praveern** [comment]
Does the value in the second dimension mean the index of the dimension?
Example: 2 --> 'H', 3 --> 'W' ? Am I correct in my thought process here?

Thanks!

**Comment by berangerd** [comment]
I'm not sure I understand your question. `flows` is a tensor of rank 4. `flows[:, 0, :, :]` represent the shifts (for given pixels in given images) along the y axis, while `flows[:, 1, :, :]` represent the shifts along the x axis.
